config/routes.rb
Rails.application.routes.draw do
  resources :adhocs do
    resources :bids
  end
  
  root 'adhocs#index'
end

app/models/adhoc.rb
class Adhoc < ActiveRecord::Base
  has_many :bids, dependent: :destroy
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :adhoc
end

app/controllers/adhocs_controller.rb
class AdhocsController < ApplicationController
  before_action :set_adhoc, only: [:show, :edit, :update, :destroy]

  # GET /adhocs
  # GET /adhocs.json
  def index
    @adhocs = Adhoc.all
  end

  # GET /adhocs/1
  # GET /adhocs/1.json
  def show
  end

  # GET /adhocs/new
  def new
    @adhoc = Adhoc.new
  end

  # GET /adhocs/1/edit
  def edit
  end

  # POST /adhocs
  # POST /adhocs.json
  def create
    @adhoc = Adhoc.new(adhoc_params)

    respond_to do |format|
      if @adhoc.save
        format.html { redirect_to @adhoc, notice: 'Adhoc was successfully created.' }
        format.json { render :show, status: :created, location: @adhoc }
      else
        format.html { render :new }
        format.json { render json: @adhoc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adhocs/1
  # PATCH/PUT /adhocs/1.json
  def update
    respond_to do |format|
      if @adhoc.update(adhoc_params)
        format.html { redirect_to @adhoc, notice: 'Adhoc was successfully updated.' }
        format.json { render :show, status: :ok, location: @adhoc }
      else
        format.html { render :edit }
        format.json { render json: @adhoc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adhocs/1
  # DELETE /adhocs/1.json
  def destroy
    @adhoc.destroy
    respond_to do |format|
      format.html { redirect_to adhocs_url, notice: 'Adhoc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adhoc
      @adhoc = Adhoc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adhoc_params
      params.require(:adhoc).permit(:orig, :depart, :dest, :arrive, :type_of_freight, :reason)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController


  def index
    @bids = Bid.all
  end

  def create
    @adhoc = Adhoc.find(params[:adhoc_id])
    @bid = @adhoc.bids.create(params[:bid].permit(:price, :miles))

    redirect_to adhoc_path(@adhoc)
  end

  def destroy
    @adhoc = Adhoc.find(params[:id])
    @bid = @adhoc.bids.find(params[:id])
    @bid.destroy

    redirect_to root_path
  end


end

app/helpers/adhocs_helper.rb
module AdhocsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/adhocs/_form.html.erb
<%= form_for(@adhoc) do |f| %>
  <% if @adhoc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adhoc.errors.count, "error") %> prohibited this adhoc from being saved:</h2>

      <ul>
      <% @adhoc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :orig %><br>
    <%= f.text_field :orig %>
  </div>
  <div class="field">
    <%= f.label :depart %><br>
    <%= f.text_field :depart %>
  </div>
  <div class="field">
    <%= f.label :dest %><br>
    <%= f.text_field :dest %>
  </div>
  <div class="field">
    <%= f.label :arrive %><br>
    <%= f.text_field :arrive %>
  </div>
  <div class="field">
    <%= f.label :type_of_freight %><br>
    <%= f.text_field :type_of_freight %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adhocs/edit.html.erb
<h1>Editing Adhoc</h1>

<%= render 'form' %>

<%= link_to 'Show', @adhoc %> |
<%= link_to 'Back', adhocs_path %>

app/views/adhocs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Adhocs</h1>

<table>
  <thead>
    <tr>
      <th>Orig</th>
      <th>Depart</th>
      <th>Dest</th>
      <th>Arrive</th>
      <th>Type of freight</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adhocs.each do |adhoc| %>
      <tr>
        <td><%= adhoc.orig %></td>
        <td><%= adhoc.depart %></td>
        <td><%= adhoc.dest %></td>
        <td><%= adhoc.arrive %></td>
        <td><%= adhoc.type_of_freight %></td>
        <td><%= adhoc.reason %></td>
        <td><%= link_to 'Show', adhoc %> |</td>
        <td><%= link_to 'Edit', edit_adhoc_path(adhoc) %> |</td>
        <td><%= link_to 'Destroy', adhoc, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adhoc', new_adhoc_path %>

app/views/adhocs/new.html.erb
<h1>New Adhoc</h1>

<%= render 'form' %>

<%= link_to 'Back', adhocs_path %>

app/views/adhocs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Orig:</strong>
  <%= @adhoc.orig %>
</p>

<p>
  <strong>Depart:</strong>
  <%= @adhoc.depart %>
</p>

<p>
  <strong>Dest:</strong>
  <%= @adhoc.dest %>
</p>

<p>
  <strong>Arrive:</strong>
  <%= @adhoc.arrive %>
</p>

<p>
  <strong>Type of freight:</strong>
  <%= @adhoc.type_of_freight %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @adhoc.reason %>
</p>

<%= link_to 'Edit', edit_adhoc_path(@adhoc) %> |
<%= link_to 'Back', adhocs_path %> |
<%= link_to 'View Bids', adhoc_bids_path(@adhoc) %>
<br>
<h3>Enter your Bid below </h3>
<%= render 'bids/form' %>

app/views/bids/_form.html.erb
<%= form_for([@adhoc, @adhoc.bids.build]) do |f| %>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.label :miles %><br>
    <%= f.text_field :miles %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/bids/index.html.erb
<table>
  <tbody>
      <% @bids.each do |bid| %>
        <tr>
          <td><%= bid.adhoc_id %></td>
          <td><%= bid.price %></td>
          <td><%= bid.miles %></td>
        </tr>


      <% end %>
    </tbody>
</table>

    <%= link_to "Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>